# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinknight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
