# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinknight', '0003_auto_20170906_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDrinkData',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('volume_dose', models.FloatField(default=b'0')),
            ],
        ),
        migrations.CreateModel(
            name='MonthDrinkData',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('volume_dose', models.FloatField(default=b'0')),
            ],
        ),
        migrations.CreateModel(
            name='YearDrinkData',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('volume_dose', models.FloatField(default=b'0')),
            ],
        ),
    ]
